In [1]:
import pandas as pd
from pathlib import Path
import csd as c

## Find counter prices

In [2]:
df = c.pull_counter_price()

C:\Users\franc\miniconda3\envs\work\lib\site-packages\pandas\io\sql.py:761: UserWarning: pandas only support SQLAlchemy connectable(engine/connection) ordatabase string URI or sqlite3 DBAPI2 connectionother DBAPI2 objects are not tested, please consider using SQLAlchemy
  warnings.warn(

run_query took 12.584355115890503s

In [3]:
df.head()

,pdrecno,startdt,enddt,levelcd,prcmult_1,prod,description,refer,status,lastuseddt
0,5847,2007-06-22,2029-12-30,7,205.0,01-ICP578,None,Level 7 Pricing Load,Active,2022-12-27
1,90378,2022-10-13,None,7,275.0,14098,1/2 J-Channel WHITE,AR 12/20/22,Active,2022-12-20
2,400,2021-06-02,2039-12-30,7,190.0,55101001,REDUCING TEE 8X8X3 26GA.,6400 FIX 8/16/21,Active,2021-09-23
3,401,2021-06-02,2039-12-30,7,200.0,55101002,REDUCING TEE 4X4X3 26GA.,6400 FIX 8/16/21,Active,2021-09-23
4,63800,2021-06-02,2029-12-30,7,200.0,55201001,"5"" VERT OVAL 90D ELBOW",6400 FIX 8/16/21,Active,2022-07-12

## <span style="color:red"> Change vendor name in last part of file path

In [4]:
loc = Path.cwd().parent / 'data' / 'merfish_product_info.csv'
products_df = pd.read_csv(loc)

In [5]:
products_df.head()

,whse,vendno,name,prod,descrip_1,descrip_2,mfgprod,vendprod,pricetype,prodcat,...,replcost,replcostdt,stndcost,stndcostdt,priceonty,prcmult_1,t12m_sales,qtyonhand,qtyonorder,stndprice
0,801,86125,MERFISH UNITED,CPF3012,"1""X20' ""M"" COPPER PIPE",NaN,NaN,NaN,638,6380,...,75.68,2021-11-08,75.68,2021-11-08,C,2.31,NaN,8.0,0.0,174.82
1,801,86125,MERFISH UNITED,CPF3013A,"1-1/4""X10' ""M"" COPPER",PIPE,NaN,NaN,638,6380,...,50.18,2021-08-16,50.18,2021-08-16,L,1.00,586.62,4.0,0.0,50.18
2,801,86125,MERFISH UNITED,CPF3115,"3/4""X50' REFRIG. COIL",COPPER,100178,100178,638,6380,...,126.67,2021-11-08,126.67,2021-11-08,L,1.00,24055.18,13.0,10.0,126.67
3,801,86125,MERFISH UNITED,CPF3001,"3/4""X20' ""L"" COPPER",PIPE,NaN,NaN,638,6380,...,68.09,2021-11-08,68.09,2021-11-08,L,1.00,1610.55,10.0,0.0,68.09
4,801,86125,MERFISH UNITED,CPF3110,"1/4"" X 50' REFRIG. COIL",COPPER,100173,100173,638,6380,...,39.65,2021-11-08,39.65,2021-11-08,L,1.00,923.80,2.0,0.0,39.65

In [6]:
PT_7_PRs_df = pd.DataFrame()

for item in products_df['prod']:
    partial_df = df.loc[df['prod'] == item]
    PT_7_PRs_df = pd.concat([PT_7_PRs_df,partial_df])

In [7]:
PT_7_PRs_df.head()

,pdrecno,startdt,enddt,levelcd,prcmult_1,prod,description,refer,status,lastuseddt
3779,2474,2021-05-06,2029-12-30,7,231.0,CPF3012,"1""X20' ""M"" COPPER PIPE",HVAC FIX 8/19,Active,2022-09-14
3782,2477,2021-05-06,2029-12-30,7,100.0,CPF3013A,"1-1/4""X10' ""M"" COPPER PIPE",HVAC FIX 8/19,Active,2022-09-14
3802,2497,2021-05-06,2029-12-30,7,100.0,CPF3115,"3/4""X50' REFRIG. COIL COPPER",HVAC FIX 8/19,Active,2023-01-05
3772,2468,2021-05-06,2029-12-30,7,100.0,CPF3001,"3/4""X20' ""L"" COPPER PIPE",HVAC FIX 8/19,Active,2022-09-14
3795,2490,2021-05-06,2029-12-30,7,100.0,CPF3110,"1/4"" X 50' REFRIG. COIL COPPER",HVAC FIX 8/19,Active,2023-01-05

In [8]:
PT_7_PRs_df.shape

(75, 10)

## <span style="color:red"> Change vendor name in last part of vendor path

In [10]:
loc = Path.cwd().parent / 'data' / 'merfish_PT_7_PRs.csv'
PT_7_PRs_df.to_csv(loc, index=False)